---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: cryfold
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - cryfold=1.0.0
  - python>=3.8
  - pip
  - pip:
    - numpy>=1.19.2
    - scipy>=1.7.0
    - pandas>=1.3.0
    - biopython>=1.79
    - torch>=1.9.0
    - torchvision>=0.10.0
    - openmm>=7.5.1
    - pdbfixer>=1.7
    - mdtraj>=1.9.5
    - boto3>=1.26.0  # AWS SDK for Python
    - awscli>=1.27.0  # AWS Command Line Interface
    - s3fs>=2023.1.0  # S3 filesystem support
